# Generated by Django 4.1 on 2023-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_id_grupo_id_grupo_estudiante_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='imagen',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numCta',
            field=models.IntegerField(default=0),
        ),
    ]
