# Generated by Django 4.1.6 on 2023-03-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='id',
            new_name='id_grupo',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.grupo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numCta',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
