# Generated by Django 4.1.6 on 2023-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_anuncio_orden_active_orden_helado_escogido_promocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(
                decimal_places=2, max_digits=100, null=True),
        ),
    ]
