# Generated by Django 4.1.6 on 2023-05-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_orden_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='promocion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cupones',
                to='mainApp.promocion'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='orden',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pedidos',
                to='mainApp.orden'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='platillo',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pedidos',
                to='mainApp.platillo'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='platillos',
                to='mainApp.categoria'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='subcategoria',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='platillos',
                to='mainApp.subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subcategorias',
                to='mainApp.categoria'),
        ),
    ]
