# Generated by Django 4.1.6 on 2023-05-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_cupon_promocion_alter_orden_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagen',
            field=models.TextField(default='', max_length=500),
        ),
    ]
