# Generated by Django 4.1.6 on 2023-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='ingredientes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
