# Generated by Django 4.1.6 on 2023-05-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_platillo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='orden',
        ),
        migrations.AddField(
            model_name='carrito',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
