# Generated by Django 4.1.6 on 2023-05-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_remove_orden_active_remove_pedido_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to='mainApp.orden'),
        ),
    ]
