# Generated by Django 4.1.6 on 2023-05-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_carrito_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='mainApp.carrito'),
        ),
    ]
