# Generated by Django 4.1.6 on 2023-05-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_pedido_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
