# Generated by Django 4.1.6 on 2023-06-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_orden_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='alergenos',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
