version: "3.9"

services:
  web:
    build: ./50Amigos
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./50Amigos/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 50amigos
      POSTGRES_PASSWORD: 50amigos
      POSTGRES_USER: 50amigos

volumes:
  postgres_data: